# Generated by Django 4.0.5 on 2022-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtag', '0004_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nl_title',
        ),
    ]
